### 유저 회원 가입
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "username":"qweqwe",
  "password":"qweqwe",
  "name":"qweqwe",
  "email":"qweqwe",
  "address": "화성시",
  "nickname": "Jack21"
}


### 로그인
POST http://localhost:8080/v1/users/login
Content-Type: application/json

{
  "username":"qweqwe",
  "password":"qweqwe"
}
> {%
  client.log(response.headers.valueOf("Authorization"));
  client.log(response.headers.valueOf("RefreshToken"));
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}


### 카테고리 추가하기
POST http://localhost:8080/v1/categories
Authorization: {{Authorization}}
Content-Type: application/json

{
  "categoryName": "중고"
}


### 상품 등록하기
POST http://localhost:8080/v1/products
Authorization: {{Authorization}}
Content-Type: application/json

{
  "productCreateDto": {
    "productName": "상품1",
    "description": "상품 설명입니다",
    "auctionNowPrice": 1000,
    "startPrice": 1000,
    "currentPrice": 1200,
    "dueDate": 1,
    "categoryName": "중고"
  },
  "productImagesRequestDto": {
    "imagesUrl": [
      "https://itsminebucket.s3.ap-northeast-2.amazonaws.com/Irelia_1.jpg",
      "https://itsminebucket.s3.ap-northeast-2.amazonaws.com/Akali_2.jpg",
      "https://itsminebucket.s3.ap-northeast-2.amazonaws.com/Irelia_3.jpg"
    ]
  }
}


### 특정 상품 조회하기
GET http://localhost:8080/products/1
Authorization: {{Authorization}}
Content-Type: application/json



### 특정 유저 상품 조회 페이지네이션
GET http://localhost:8080/products/user?page=0&size=5
Authorization: {{Authorization}}
Content-Type: application/json


### 모든 상품 조회 페이지네이션
GET http://localhost:8080/products/all?page=0&size=5
Authorization: {{Authorization}}
Content-Type: application/json


### 좋아요 누르기
POST http://localhost:8080/v1/users/products/1/likes
Authorization: {{Authorization}}
Content-Type: application/json


### 좋아요 게시물 조회
GET http://localhost:8080/products/likes?page=0&size=5
Authorization: {{Authorization}}
Content-Type: application/json



### 상품 수정
PATCH http://localhost:8080/products/3
Authorization: {{Authorization}}
Content-Type: application/json

{
  "productName": "이정빈"
}


### 상품 좋아요
POST http://localhost:8080/products/3/likes
Authorization: {{Authorization}}
Content-Type: application/json


### 상품 삭제
DELETE http://localhost:8080/products/1
Authorization: {{Authorization}}
Content-Type: application/json

