### 유저 회원 가입
POST https://localhost:443/users
Content-Type: application/json

{
  "username":"seongchankim",
  "password":"12345678!@#ASD",
  "name":"김성찬",
  "email":"seongchankim@asd.com",
  "address": "서울시",
  "nickname": "SCK"
}

### 로그인
POST https://localhost:443/users/login
Content-Type: application/json

{
  "username":"seongchankim",
  "password":"12345678!@#ASD"
}
> {%client.global.set("Authorization", response.headers.valueOf("Authorization"));%}


### 로그아웃
GET https://localhost:443/users/logout
Content-Type: application/json
Authorization: {{Authorization}}


### 유저 조회
GET https://localhost:443/users/1
Content-Type: application/json
Authorization: {{Authorization}}


### 회원 탈퇴
DELETE https://localhost:443/users/withdraw
Content-Type: application/json
Authorization: {{Authorization}}

### 회원 복구
PUT https://localhost:443/users/resign/5
Content-Type: application/json
Authorization: {{Authorization}}

### 회원 정보 수정
PUT https://localhost:443/users/update
Content-Type: application/json
Authorization: {{Authorization}}

{

  "email":"seongchankim1@asd.com",
  "address": "서울시2",
  "nickname": "SCK3"
}
